services:
    db:
        build: ./backend/db
        image: my-postgres-db
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
        env_file:
            - ./backend/.env
        environment:
            POSTGRES_PASSWORD: your_postgres_password
    app:
        build: ./backend/app
        image: my-node-app
        ports:
            - 3000:3000
        depends_on:
            - db
        env_file:
            - ./backend/.env
    frontend:
        build: ./frontend
        ports:
            - "4000:4000"

volumes:
    db-data:
