services:
    db:
        build: ./backend/db
        image: my-postgres-db
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
    app:
        build: ./backend/app
        image: my-node-app
        ports:
            - 3000:3000
        depends_on:
            - db
        environment:
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_HOST: ${DB_HOST}
            DB_NAME: ${DB_NAME}
    frontend:
        build: ./frontend
        ports:
            - "4000:4000"
        volumes:
            - ./frontend:/app
        stdin_open: true
        tty: true
